INSERT INTO `tmz`.`users` (`recid`, `login`, `password`, `role`, `enabled`, `created_at`, `created_by`, `updated_at`, `updated_by`, `version`)
VALUES ('1', 'user', 'user', 'ROLE_USER', '1', '2000-11-11 11:11:11', 'user', '2000-11-11 11:11:11', 'user', '1');
INSERT INTO `tmz`.`users` (`recid`, `login`, `password`, `role`, `enabled`, `created_at`, `created_by`, `updated_at`, `updated_by`, `version`)
VALUES ('2', 'admin', 'admin', 'ROLE_ADMIN', '1', '2000-11-11 11:11:11', 'admin', '2000-11-11 11:11:11', 'admin', '1');

INSERT INTO `tmz`.`authorities` (`recid`, `authority`, `created_at`, `created_by`, `login`, `updated_at`, `updated_by`, `version`)
VALUES ('1', 'ROLE_USER', '2000-11-11 11:11:11', 'user', 'user', '2000-11-11 11:11:11', 'user', '1');
INSERT INTO `tmz`.`authorities` (`recid`, `authority`, `created_at`, `created_by`, `login`, `updated_at`, `updated_by`, `version`)
VALUES ('2', 'ROLE_ADMIN', '2000-11-11 11:11:11', 'admin', 'admin', '2000-11-11 11:11:11', 'admin', '1');

INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (1, 'Aerosoles');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (2, 'Calba');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (3, 'Flexx');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (4, 'Fraven');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (5, 'Ibershoes');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (6, 'Ko&Ko');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (7, 'M&G');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (8, 'Maritan');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (9, 'Америка');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (10, 'Амин');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (11, 'Бельгия');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (12, 'Глобал Фут');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (13, 'Маркезини');
INSERT INTO `tmz`.`factorytable` (`recid`, `name`) VALUES (14, 'Эспадрильи');

INSERT INTO `tmz`.`seasons` (`recid`, `name`) VALUES (1, 'FW 13-14');
INSERT INTO `tmz`.`seasons` (`recid`, `name`) VALUES (2, 'FW 14-15');
INSERT INTO `tmz`.`seasons` (`recid`, `name`) VALUES (3, 'SS 13');
INSERT INTO `tmz`.`seasons` (`recid`, `name`) VALUES (4, 'SS 14');

INSERT INTO `tmz`.`toe` (`recid`, `name`) VALUES (1, 'Гладкая');
INSERT INTO `tmz`.`toe` (`recid`, `name`) VALUES (2, 'Отрезная');
INSERT INTO `tmz`.`toe` (`recid`, `name`) VALUES (3, 'Инспектор');
INSERT INTO `tmz`.`toe` (`recid`, `name`) VALUES (4, 'Мокасиновые');
INSERT INTO `tmz`.`toe` (`recid`, `name`) VALUES (5, 'Крокодил');

INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (1, 'PU');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (2, 'SBS');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (3, 'ТЭП');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (4, 'ПВХ');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (5, 'ТУНИТ');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (6, 'КОЖА');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (7, 'КОЖА+ПРОФИЛАКТИКА');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (8, 'EVA');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (9, 'RABBA');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (10, 'Ingection Rabba');
INSERT INTO `tmz`.`soleMaterial` (`recid`, `name`) VALUES (11, 'TPR');


INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (1, 'Клеевой');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (2, 'Штробель');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (3, 'Полуштробель');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (4, 'Бортопрошивной');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (5, 'Сакето(с губой)');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (6, 'Калифиорния(втачная стелька)');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (7, 'Вывортно-прошивной(флекс)');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (8, 'Мокасин');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (9, 'Сандальный');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (10, 'Внутренний клин');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (11, 'Боковое пристрачивание');
INSERT INTO `tmz`.`attachmentMethods` (`recid`, `method`) VALUES (12, 'Литьевой');


INSERT INTO `tmz`.`clientTypes` (`recid`, `name`) VALUES (1, 'Консерватор');
INSERT INTO `tmz`.`clientTypes` (`recid`, `name`) VALUES (2, 'Директор');
INSERT INTO `tmz`.`clientTypes` (`recid`, `name`) VALUES (3, 'Стиль вне времени');
INSERT INTO `tmz`.`clientTypes` (`recid`, `name`) VALUES (4, 'Модный');
INSERT INTO `tmz`.`clientTypes` (`recid`, `name`) VALUES (5, 'Тренд');

INSERT INTO `tmz`.`contextTypes` (`recid`, `name`) VALUES (1, 'Прогулка');
INSERT INTO `tmz`.`contextTypes` (`recid`, `name`) VALUES (2, 'Работа элегантный стиль');
INSERT INTO `tmz`.`contextTypes` (`recid`, `name`) VALUES (3, 'Свободный стиль');
INSERT INTO `tmz`.`contextTypes` (`recid`, `name`) VALUES (4, 'Торжество');


INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (1, 'балетки');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (2, 'босоножки');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (3, 'ботинки');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (4, 'ботинки на шнурках');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (5, 'деленка');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (6, 'кроссовки');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (7, 'мокасины');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (8, 'полуботинки');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (9, 'або открытое');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (10, 'сандалии');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (11, 'слиппер');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (12, 'сникеры');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (13, 'туфли');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (14, 'туфли закрытые');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (15, 'туфли закрытые на шнурках');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (16, 'туфли мокасиновые');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (17, 'туфли открытые');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (18, 'туфли полузакрытые');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (19, 'туфли ремешковые');
INSERT INTO `tmz`.`kindShoes` (`recid`, `name`) VALUES (20, 'шанель');

INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (1, 'anlina autanato');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (2, 'snake pig ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (3, 'alaska clint');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (4, 'anilina atanato');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (5, 'as original proto');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (6, 'asaigo');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (7, 'aspis');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (8, 'aspis finito');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (9, 'bark mez');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (10, 'big  reptail');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (11, 'big reptail');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (12, 'big reptile');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (13, 'rush off croco');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (14, 'rush off croco ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (15, 'codelia');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (16, 'cow suede');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (17, 'dali');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (18, 'dali ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (19, 'danubio brash');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (20, 'danubio brush');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (21, 'detroit');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (22, 'doublet');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (23, 'flowers');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (24, 'foulard');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (25, 'geomeluc');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (26, 'glove sheep');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (27, 'glove sheep ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (28, 'Goat pecos ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (29, 'goat pekos');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (30, 'heavy metal');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (31, 'hevy metal');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (32, 'intreccio pelle\elast');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (33, 'italia');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (34, 'kid suede');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (35, 'kis suede');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (36, 'leather print with rose');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (37, 'lucertolina');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (38, 'lucetolina');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (39, 'lucetolinna');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (40, 'naked lea');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (41, 'naked leather');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (42, 'nb');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (43, 'nb ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (44, 'new beach');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (45, 'new beach ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (46, 'new kaffir');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (47, 'new kafir');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (48, 'nubuck');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (49, 'nubuk');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (50, 'parama nappa');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (51, 'parma nappa');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (52, 'patent');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (53, 'patent ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (54, 'patent kid');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (55, 'patent soft');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (56, 'phyton');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (57, 'phyton ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (58, 'phyton print');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (59, 'polish calf');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (60, 'pony');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (61, 'pony hair ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (62, 'print snake ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (63, 'roses');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (64, 'saila brd');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (65, 'saila brp');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (66, 'sheep glove');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (67, 'sheep nappa');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (68, 'sheep nappa/elastic darker');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (69, 'snake');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (70, 'snake pig');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (71, 'snake pig ');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (72, 'snake pig roccia');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (73, 'snake pig skain');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (74, 'snake shining');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (75, 'spe aspis finito');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (76, 'taffy');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (77, 'velevet');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (78, 'velevt');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (79, 'velvet');
INSERT INTO `tmz`.`materials` (`recid`, `name`) VALUES (80, 'комуфляж. The same proto');


INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (1, '327');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (2, '2341');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (3, '3044');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (4, '7095');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (5, '7235');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (6, '7357');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (7, '70954');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (8, '73571');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (9, '82502');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (10, '03135');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (11, '07022');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (12, '2341');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (13, '3044');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (14, '3044(dk cuoio)');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (15, '3044-cuoio');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (16, '329/59B');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (17, '7095');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (18, '7235');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (19, '73571');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (20, '82502');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (21, '82621');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (22, 'air');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (23, 'atlantic(the same as dali atlantic)');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (24, 'beige');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (25, 'biscus 757');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (26, 'black');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (27, 'black graphite');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (28, 'black/white');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (29, 'black\graphile');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (30, 'blue');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (31, 'bordeau');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (32, 'bordeaux');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (33, 'bruciato');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (34, 'cameo blosh');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (35, 'cameo blush');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (36, 'cfr 6090');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (37, 'cfr 6090 roccia');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (38, 'cirtine');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (39, 'citrine 2');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (40, 'citrine CX  860');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (41, 'citrine cx860');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (42, 'citrine1');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (43, 'ckr-6090 roccia');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (44, 'colour like dublet hibiscus ss757');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (45, 'colour like glove sheep ocean');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (46, 'coral');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (47, 'coral fusion');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (48, 'cuoio');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (49, 'cyber ');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (50, 'denim jeans');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (51, 'dk blue');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (52, 'dk brown');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (53, 'dk navy');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (54, 'dream jeans');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (55, 'eclipse blue');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (56, 'electric blue');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (57, 'expresso');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (58, 'flint grey');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (59, 'frair brown');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (60, 'friar brown');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (61, 'gold');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (62, 'gold brown');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (63, 'gold dk brown');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (64, 'graphite black');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (65, 'green');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (66, 'green 5102');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (67, 'greice');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (68, 'greice   ');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (69, 'greig');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (70, 'greige');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (71, 'grige');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (72, 'grigio');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (73, 'hazel');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (74, 'irazu');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (75, 'iruze');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (76, 'jeans');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (77, 'las vegas');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (78, 'leopard');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (79, 'lipstik');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (80, 'los angeles');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (81, 'luggage');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (82, 'mauve');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (83, 'mauve 69062');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (84, 'mauve(croco)');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (85, 'navy');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (86, 'neon orange');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (87, 'new york');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (88, 'ocean');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (89, 'ocean D6825');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (90, 'ochre(yellow)');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (91, 'off white');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (92, 'orange');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (93, 'pale yellow ');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (94, 'petrol');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (95, 'pink');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (96, 'poision');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (97, 'provenza');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (98, 'proveuza');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (99, 'quarz');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (100, 'red');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (101, 'riviera');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (102, 'rubbin(dk red)');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (103, 'ruby');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (104, 'sabbia');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (105, 'sand');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (106, 'shell');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (107, 't.moro');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (108, 'taupe');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (109, 'warm taupe');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (110, 'whiskey');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (111, 'white');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (112, 'white 1100R');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (113, 'white/black');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (114, 'yellow');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (115, 'zebra');
INSERT INTO `tmz`.`colors` (`recid`, color) VALUES (116, 'комуфляж. The same proto');



